// version.h
// This file is automatically generated by CreateVersionFile.py

#define AVG_VERSION_RELEASE     "1.7.1"
#define AVG_VERSION_FULL        "1.7.1"
#define AVG_VERSION_BRANCH_URL  ""
#define AVG_VERSION_BUILDER     "lynxis@lazus Linux-3.2.13-1-ARCH-x86_64-Intel-R-_Core-TM-_i7_CPU_L_620_@_2.00GHz-with-glibc2.2.5"
#define AVG_VERSION_BUILDTIME   "2012-04-12T02:34:51.876153"
#define AVG_VERSION_REVISION    0
#define AVG_VERSION_MAJOR       1
#define AVG_VERSION_MINOR       7
#define AVG_VERSION_MICRO       1
